### ISSUE TITLE
Error : user table is not exist in yii2 basic template 

### ISSUE THREAD

**Issue by PritiPhulari** [hscstudio/yii2-mimin#3]
Kindly add User table in your migration command 

it is not exists in Yii2 Basic.
So add it 
https://github.com/yiisoft/yii2-app-advanced/blob/master/console/migrations/m130524_201442_init.php

**Comment by hscstudio** [comment]
I have added attention in readme

"Before you install and use this extension, then make sure that your application has been using the login authentication to the database. especially for yii basic template. Because without it, this extension will produce error and useless."

Because to make basic template use authentication with database its very long way to explain in here

How about You?
